language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - rm -rf ./public

script:
  - ng build --prod --base-href="https://anshulsanghi.tech/"
  - ng run portfolio:server
  - cd functions && npm install && cd ../
  - cp -a functions/dist/browser/. public/
  - mv public/index.html public/index2.html

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
